modified:   memuse

diff --git a/memuse b/memuse
--- a/memuse
+++ b/memuse
@@ -1,8 +1,46 @@
 #!/bin/bash
-# Script to display the memory usage of each running ARK Server.
+# Script to display the memory usage for each running ARK server process.
+# VIRT is the process allocated memory. RES is the actual memory the process uses.
 # Based on Phorce1's memuse.sh
 
-ps -eo size,rss,command --sort -size | awk '/ShooterGameServer/ && !/awk/ {print v"[VIRT]:",$1=int(10*$1/1024/1024)/10"GB","- [RES]:",$2=int(10*$2/1024/1024)/10"GB","!",$0}' | \
- awk -F'!|SessionName=' '{print $1,"- "$3}' | awk -F'?' '{print $1}' | column -t -s '-'
-free -h | awk '/^Mem/ {print "Total RAM: "$7"B/"$2"B"}'
-free -h | awk '/^Swap/ {print "Total Swap: "$4"B/"$2"B"}'
+syntax() {
+ echo -e "Syntax:
+  -d              - Detailed mode. Shows RES and VIRT of each process.
+  -h              - Shows this help message.
+ "
+}
+
+memuse() {
+if [ ! -z "$mode" ]; then
+  ps -eo size,rss,command --sort -size | awk '/ShooterGameServer/ && !/awk/ {print "[VIRT]:",$1=int(10*$1/1024/1024)/10"GB","- [RES]:",$2=int(10*$2/1024/1024)/10"GB","!",$0}' |
+   awk -F'!|SessionName=' '{print $1,"- "$3}' | awk -F'?' '{print $1}' | column -t -s '-'
+ else
+  ps -eo size,rss,command --sort -size | awk '/ShooterGameServer/ && !/awk/ {print "[MEM]:",$2=int(10*$2/1024/1024)/10"GB","!",$0}' |
+   awk -F'!|SessionName=' '{print $1,"- "$3}' | awk -F'?' '{print $1}' | column -t -s '-'
+ fi
+ echo
+ printf "Total RAM used by ARK servers: "
+ ps -eo size,rss,command --sort -size | awk '/ShooterGameServer/ && !/awk/ {s+=int(10*$2/1024/1024)/10} END {print s"GB"}'
+ free -h | awk '/^Mem/ {print "Used system RAM: "$3"B/"$2"B"}'
+ free -h | awk '/^Swap/ {print "Used system Swap: "$3"B/"$2"B"}'
+}
+
+while getopts ":d|:h" opt; do
+ case $opt in
+  d)
+    mode="1"
+  ;;
+  h)
+    syntax
+    exit 0
+  ;;
+  \?)
+    syntax
+    echo "Invalid option: -$OPTARG." 1>&2
+    exit 1
+  ;;
+ esac
+done
+shift $((OPTIND -1))
+
+memuse
